services:
    laravel.test:
        build:
            context: ./docker/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mongodb

    mongodb:
        image: mongo:latest
        ports:
            - "${MONGODB_PORT:-27017}:27017"
        # environment:
        #     MONGO_INITDB_ROOT_USERNAME: '${MONGODB_USERNAME}'
        #     MONGO_INITDB_ROOT_PASSWORD: '${MONGODB_PASSWORD}'
        command: mongod --replSet rs0
        healthcheck:
            test: |
                mongosh --eval "try { rs.status().ok } catch (e) { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'localhost:27017' }] }).ok }"
            start_period: 0s
            interval: 500ms
            timeout: 5s
            retries: 5
        volumes:
            - mongodb_data:/data/db
        networks:
            - sail

networks:
    sail:
        driver: bridge

volumes:
    mongodb_data:
